import React, { useEffect, useState } from 'react';
import { apiService } from '../../services/api';
import { useApp } from '../../context/AppContext';
import { Activity, AlertTriangle, ArrowDownToLine, ArrowUpRight, Banknote, Boxes, CheckCircle2, Clock3, RefreshCw, Users, MessageSquare, FileText } from 'lucide-react';

const money=(n:number)=>new Intl.NumberFormat('ar-IQ').format(Math.round(n||0));
export const ExecutiveCommandView: React.FC = () => {
  const {showToast,setActiveTab}=useApp(); const [data,setData]=useState<any>(null); const [aging,setAging]=useState<any>(null); const [loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);try{const [a,b]=await Promise.all([apiService.getExecutiveOverview(),apiService.getFinanceAging()]);setData(a);setAging(b);}catch(e:any){showToast(e.message||'تعذر تحميل مركز القيادة');}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  if(!data) return <div dir="rtl" className="p-8 text-center text-slate-400">جارٍ تحميل مركز القيادة...</div>;
  const m=data.metrics||{}, q=data.actionQueue||[];
  return <div dir="rtl" className="space-y-6">
    <div className="p-6 rounded-3xl bg-gradient-to-l from-slate-900 via-indigo-950/50 to-emerald-950/30 border border-slate-800 flex flex-col md:flex-row justify-between gap-4"><div><div className="flex items-center gap-2"><Activity className="w-5 h-5 text-emerald-400"/><h2 className="text-xl font-black text-white">مركز القيادة التنفيذي</h2></div><p className="text-xs text-slate-400 mt-2">الصورة التشغيلية والمالية الموحدة للمعرض من البيانات الفعلية المخزنة على الخادم.</p></div><button onClick={()=>void load()} disabled={loading} className="px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-xs font-black text-white flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/> تحديث شامل</button></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
      {[['إجمالي المبيعات',money(m.totalSales),'د.ع',Banknote],['المحصّل',money(m.paid),'د.ع',CheckCircle2],['الرصيد المتبقي',money(m.balance),'د.ع',ArrowDownToLine],['المتأخر',money(m.overdueBalance),'د.ع',AlertTriangle]].map(([t,v,u,I]:any)=><div key={t} className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><I className="w-4 h-4 text-emerald-400"/><p className="text-[10px] text-slate-500 mt-3">{t}</p><p className="text-xl font-black text-white mt-1">{v}</p><p className="text-[10px] text-slate-500">{u}</p></div>)}
    </div>
    <div className="grid lg:grid-cols-3 gap-4">
      <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex items-center gap-2 mb-4"><Users className="w-4 h-4 text-cyan-400"/><h3 className="font-black text-white">مسار العملاء</h3></div><div className="space-y-2">{[['جديد',data.crm.new],['مؤهل',data.crm.qualified],['عرض مقدم',data.crm.proposal],['مكتمل',data.crm.won],['غير مكتمل',data.crm.lost]].map(([k,v]:any)=><div className="flex justify-between p-2.5 rounded-xl bg-slate-950/60" key={k}><span className="text-xs text-slate-300">{k}</span><b className="text-white">{v}</b></div>)}</div></div>
      <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex items-center gap-2 mb-4"><Boxes className="w-4 h-4 text-amber-400"/><h3 className="font-black text-white">المخزون</h3></div><div className="grid grid-cols-2 gap-2">{[['الوحدات',data.inventory.totalUnits],['المنتجات',data.inventory.products],['منخفض',data.inventory.low],['نافد',data.inventory.out]].map(([k,v]:any)=><div className="p-3 rounded-xl bg-slate-950/60" key={k}><p className="text-[10px] text-slate-500">{k}</p><b className="text-lg text-white">{v}</b></div>)}</div></div>
      <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex items-center gap-2 mb-4"><Clock3 className="w-4 h-4 text-rose-400"/><h3 className="font-black text-white">طابور الإجراءات</h3></div>{q.length===0?<p className="text-xs text-emerald-300">لا توجد إجراءات حرجة حاليًا.</p>:<div className="space-y-2">{q.map((x:any)=><button key={x.id} onClick={()=>x.type==='finance'?setActiveTab('finance'):x.type==='crm'?setActiveTab('operations'):x.type==='content'?setActiveTab('approval'):x.type==='messages'?setActiveTab('customers'):x.type==='tasks'?setActiveTab('operations'):setActiveTab('system')} className="w-full text-right p-3 rounded-xl bg-slate-950/60 border border-slate-800 hover:border-slate-600"><div className="flex justify-between gap-2"><span className="text-xs font-bold text-white">{x.label}</span><span className="text-[10px] text-amber-300">{x.count}</span></div>{x.value>0&&<p className="text-[10px] text-rose-300 mt-1">{money(x.value)} د.ع</p>}</button>)}</div>}</div>
    </div>
    <section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><ArrowUpRight className="w-4 h-4 text-indigo-400"/><h3 className="font-black text-white">أعمار الأرصدة المستحقة</h3></div><span className="text-[10px] text-slate-500">{aging?.summary?.count||0} عملية مفتوحة</span></div><div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['الحالي',data.aging.current],['1–30 يوم',data.aging.days1to30],['31–60 يوم',data.aging.days31to60],['61–90 يوم',data.aging.days61to90],['أكثر من 90',data.aging.over90]].map(([k,v]:any)=><div className="p-4 rounded-xl bg-slate-950/60 border border-slate-800" key={k}><p className="text-[10px] text-slate-500">{k}</p><p className="text-sm font-black text-white mt-1">{money(v)} <span className="text-[9px] text-slate-500">د.ع</span></p></div>)}</div></section>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><button onClick={()=>setActiveTab('finance')} className="p-4 rounded-2xl bg-slate-900 border border-slate-800 text-right"><Banknote className="w-4 h-4 text-emerald-400 mb-2"/><b className="text-xs text-white">المالية والتحصيل</b></button><button onClick={()=>setActiveTab('inventory')} className="p-4 rounded-2xl bg-slate-900 border border-slate-800 text-right"><Boxes className="w-4 h-4 text-amber-400 mb-2"/><b className="text-xs text-white">المخزون</b></button><button onClick={()=>setActiveTab('customers')} className="p-4 rounded-2xl bg-slate-900 border border-slate-800 text-right"><MessageSquare className="w-4 h-4 text-cyan-400 mb-2"/><b className="text-xs text-white">خدمة العملاء</b></button><button onClick={()=>setActiveTab('reports')} className="p-4 rounded-2xl bg-slate-900 border border-slate-800 text-right"><FileText className="w-4 h-4 text-indigo-400 mb-2"/><b className="text-xs text-white">التقارير</b></button></div>
  </div>;
};
