import React, { useState } from 'react';
import { Search, Package, FileText, MessageSquare, Loader2 } from 'lucide-react';
import { apiService } from '../../services/api';

export const GlobalSearchView: React.FC = () => {
  const [q,setQ]=useState(''); const [loading,setLoading]=useState(false); const [data,setData]=useState<any>(null); const [error,setError]=useState('');
  const submit=async(e:React.FormEvent)=>{e.preventDefault(); if(q.trim().length<2){setError('اكتب كلمتين على الأقل للبحث.');return;} setError('');setLoading(true);try{setData(await apiService.searchWorkspace(q));}catch(err:any){setError(err.message||'تعذر البحث');}finally{setLoading(false)}};
  return <div className="space-y-6"><div className="p-6 rounded-2xl bg-slate-900 border border-slate-800"><h2 className="text-xl font-black text-white flex items-center gap-2"><Search className="w-5 h-5 text-emerald-400"/> البحث الموحد</h2><p className="text-xs text-slate-400 mt-1">بحث واحد داخل المنتجات والمحتوى والمحادثات المحفوظة. لا يستخدم Gemini.</p><form onSubmit={submit} className="mt-5 flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم منتج، عميل، منشور..." className="flex-1 bg-slate-950 border border-slate-700 rounded-xl px-4 py-3 text-sm text-white outline-none focus:border-emerald-500"/><button disabled={loading} className="px-5 rounded-xl bg-emerald-500 text-slate-950 font-black text-sm flex items-center gap-2">{loading?<Loader2 className="w-4 h-4 animate-spin"/>:<Search className="w-4 h-4"/>} بحث</button></form>{error&&<p className="text-xs text-rose-300 mt-3">{error}</p>}</div>{data&&<div className="grid lg:grid-cols-3 gap-5"><Result title="المنتجات" icon={Package} items={data.results.products} render={(x:any)=>`${x.name} • ${Number(x.cashPrice||0).toLocaleString()} د.ع`}/><Result title="المحتوى" icon={FileText} items={data.results.posts} render={(x:any)=>`${x.title||'منشور'} • ${x.status||''}`}/><Result title="المحادثات" icon={MessageSquare} items={data.results.conversations} render={(x:any)=>`${x.customerName} • ${x.lastMessage||''}`}/></div>}</div>;
};
const Result:React.FC<{title:string;icon:any;items:any[];render:(x:any)=>string}>=({title,icon:Icon,items,render})=><section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-bold text-white flex items-center gap-2 mb-3"><Icon className="w-4 h-4 text-emerald-400"/>{title}<span className="text-[10px] text-slate-500">{items.length}</span></h3>{items.length?<div className="space-y-2 max-h-96 overflow-auto">{items.map((x:any)=><div key={x.id} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800"><p className="text-xs text-slate-200 leading-5">{render(x)}</p></div>)}</div>:<p className="text-xs text-slate-500">لا توجد نتائج.</p>}</section>;
