import React, { useEffect, useMemo, useState } from 'react';
import { apiService } from '../../services/api';
import { useApp } from '../../context/AppContext';
import { ClipboardList, UserPlus, RefreshCw, CheckCircle2, Clock3, Plus, Trash2 } from 'lucide-react';

const statusLabels: Record<string,string> = { new:'جديد', contacted:'تم التواصل', qualified:'مؤهل', proposal:'عرض مقدم', won:'مكتمل', lost:'غير مكتمل' };
const taskLabels: Record<string,string> = { open:'مفتوحة', in_progress:'قيد التنفيذ', done:'منجزة', cancelled:'ملغاة' };

export const OperationsView: React.FC = () => {
  const { showToast } = useApp();
  const [leads,setLeads]=useState<any[]>([]); const [tasks,setTasks]=useState<any[]>([]); const [loading,setLoading]=useState(false);
  const [leadName,setLeadName]=useState(''); const [leadPhone,setLeadPhone]=useState(''); const [leadProduct,setLeadProduct]=useState('');
  const [taskTitle,setTaskTitle]=useState(''); const [taskDue,setTaskDue]=useState('');
  const load=async()=>{setLoading(true);try{const [l,t]=await Promise.all([apiService.getLeads(),apiService.getTasks()]);setLeads(l);setTasks(t);}catch(e:any){showToast(e.message||'تعذر تحميل مركز العمليات');}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const pipeline=useMemo(()=>Object.fromEntries(Object.keys(statusLabels).map(k=>[k,leads.filter(x=>x.status===k).length])),[leads]);
  const addLead=async()=>{if(!leadName.trim()){showToast('اسم العميل مطلوب');return;}try{const lead=await apiService.createLead({customerName:leadName,phone:leadPhone,interestedProduct:leadProduct});setLeads(x=>[lead,...x]);setLeadName('');setLeadPhone('');setLeadProduct('');showToast('تمت إضافة العميل المحتمل');}catch(e:any){showToast(e.message)}};
  const addTask=async()=>{if(!taskTitle.trim()){showToast('عنوان المهمة مطلوب');return;}try{const task=await apiService.createTask({title:taskTitle,dueAt:taskDue||undefined});setTasks(x=>[task,...x]);setTaskTitle('');setTaskDue('');showToast('تمت إضافة المهمة');}catch(e:any){showToast(e.message)}};
  const updateLead=async(id:string,status:string)=>{try{const lead=await apiService.updateLead(id,{status});setLeads(x=>x.map(a=>a.id===id?lead:a));}catch(e:any){showToast(e.message)}};
  const updateTask=async(id:string,status:string)=>{try{const task=await apiService.updateTask(id,{status});setTasks(x=>x.map(a=>a.id===id?task:a));}catch(e:any){showToast(e.message)}};
  const deleteTask=async(id:string)=>{try{await apiService.deleteTask(id);setTasks(x=>x.filter(a=>a.id!==id));showToast('تم حذف المهمة');}catch(e:any){showToast(e.message)}};
  return <div dir="rtl" className="space-y-6">
    <div className="p-6 rounded-2xl bg-gradient-to-l from-slate-900 to-indigo-950/40 border border-indigo-500/20 flex flex-col md:flex-row justify-between gap-4"><div><h2 className="text-xl font-black text-white flex items-center gap-2"><ClipboardList className="w-5 h-5 text-indigo-400"/> مركز العمليات والمتابعة</h2><p className="text-xs text-slate-400 mt-1">إدارة العملاء المحتملين، المتابعات والمهام الداخلية من مصدر بيانات واحد.</p></div><button onClick={()=>void load()} disabled={loading} className="px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-xs font-bold text-white flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/> تحديث</button></div>
    <div className="grid grid-cols-2 md:grid-cols-6 gap-3">{Object.entries(statusLabels).map(([k,v])=><div key={k} className="p-4 rounded-2xl bg-slate-900 border border-slate-800"><p className="text-[10px] text-slate-500">{v}</p><p className="text-2xl font-black text-white mt-1">{pipeline[k]||0}</p></div>)}</div>
    <div className="grid lg:grid-cols-2 gap-6">
      <section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-black text-white flex items-center gap-2 mb-4"><UserPlus className="w-4 h-4 text-emerald-400"/> إضافة عميل محتمل</h3><div className="grid gap-2"><input value={leadName} onChange={e=>setLeadName(e.target.value)} placeholder="اسم العميل" className="input"/><input value={leadPhone} onChange={e=>setLeadPhone(e.target.value)} placeholder="رقم الهاتف (اختياري)" className="input"/><input value={leadProduct} onChange={e=>setLeadProduct(e.target.value)} placeholder="المنتج المهتم به (اختياري)" className="input"/><button onClick={()=>void addLead()} className="btn-primary"><Plus className="w-4 h-4"/> إضافة</button></div></section>
      <section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-black text-white flex items-center gap-2 mb-4"><Clock3 className="w-4 h-4 text-cyan-400"/> إنشاء مهمة متابعة</h3><div className="grid gap-2"><input value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="مثال: متابعة طلب عميل" className="input"/><input type="datetime-local" value={taskDue} onChange={e=>setTaskDue(e.target.value)} className="input"/><button onClick={()=>void addTask()} className="btn-primary"><Plus className="w-4 h-4"/> إنشاء المهمة</button></div></section>
    </div>
    <div className="grid lg:grid-cols-2 gap-6">
      <section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex justify-between mb-4"><h3 className="font-black text-white">العملاء المحتملون</h3><span className="text-[10px] text-slate-500">{leads.length}</span></div>{leads.length===0?<p className="text-xs text-slate-500">لا توجد بيانات بعد.</p>:<div className="space-y-2 max-h-[520px] overflow-auto">{leads.map(l=><div key={l.id} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800"><div className="flex justify-between gap-3"><div><p className="text-sm font-bold text-white">{l.customerName}</p><p className="text-[10px] text-slate-500">{l.phone||'بدون رقم'} {l.interestedProduct?`• ${l.interestedProduct}`:''}</p></div><select value={l.status} onChange={e=>void updateLead(l.id,e.target.value)} className="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-[10px] text-white">{Object.entries(statusLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{l.nextFollowUpAt&&<p className="text-[10px] text-cyan-300 mt-2">متابعة: {new Date(l.nextFollowUpAt).toLocaleString('ar-IQ')}</p>}</div>)}</div>}</section>
      <section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex justify-between mb-4"><h3 className="font-black text-white">مهام الفريق</h3><span className="text-[10px] text-slate-500">{tasks.length}</span></div>{tasks.length===0?<p className="text-xs text-slate-500">لا توجد مهام بعد.</p>:<div className="space-y-2 max-h-[520px] overflow-auto">{tasks.map(t=><div key={t.id} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800"><div className="flex justify-between gap-3"><div><p className="text-sm font-bold text-white">{t.title}</p><p className="text-[10px] text-slate-500">{t.dueAt?new Date(t.dueAt).toLocaleString('ar-IQ'):'بدون موعد'} • {taskLabels[t.status]||t.status}</p></div><div className="flex gap-1"><select value={t.status} onChange={e=>void updateTask(t.id,e.target.value)} className="bg-slate-900 border border-slate-700 rounded-lg px-2 py-1 text-[10px] text-white">{Object.entries(taskLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><button onClick={()=>void deleteTask(t.id)} className="p-1.5 rounded-lg bg-rose-950/40 text-rose-300"><Trash2 className="w-3.5 h-3.5"/></button></div></div>{t.status==='done'&&<div className="mt-2 text-[10px] text-emerald-300 flex items-center gap-1"><CheckCircle2 className="w-3 h-3"/> مكتملة</div>}</div>)}</div>}</section>
    </div>
    <style>{`.input{background:#020617;border:1px solid #334155;border-radius:12px;padding:.7rem .85rem;color:white;font-size:.75rem;outline:none}.input:focus{border-color:#10b981}.btn-primary{background:#10b981;color:#020617;border-radius:12px;padding:.7rem;font-size:.75rem;font-weight:900;display:flex;align-items:center;justify-content:center;gap:.35rem}`}</style>
  </div>;
};
