import React,{useEffect,useState} from 'react';
import {apiService} from '../../services/api';
import {useApp} from '../../context/AppContext';
import {Banknote,CheckCircle2,Plus,RefreshCw,ShoppingCart,Wallet} from 'lucide-react';
const money=(n:number)=>`${Math.round(n||0).toLocaleString('ar-IQ')} د.ع`;
export const SalesCenterView:React.FC=()=>{
 const {showToast}=useApp(); const [sales,setSales]=useState<any[]>([]),[products,setProducts]=useState<any[]>([]),[loading,setLoading]=useState(false),[selected,setSelected]=useState<any>(null);
 const [customerName,setCustomerName]=useState(''),[phone,setPhone]=useState(''),[productId,setProductId]=useState(''),[total,setTotal]=useState(''),[down,setDown]=useState('0'),[months,setMonths]=useState('12'),[payment,setPayment]=useState('');
 const load=async()=>{setLoading(true);try{const [s,p]=await Promise.all([apiService.getSales(),apiService.getWorkspaceProducts()]);setSales(s);setProducts(p)}catch(e:any){showToast(e.message||'تعذر تحميل المبيعات')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const create=async()=>{const p=products.find(x=>x.id===productId);if(!customerName.trim()||!p||Number(total)<=0){showToast('اسم العميل والمنتج وقيمة البيع مطلوبة');return}try{const sale=await apiService.createSale({customerName,phone,productId:p.id,productName:p.name,totalAmount:Number(total),downPayment:Number(down)||0,months:Number(months)||1});setSales(x=>[sale,...x]);setCustomerName('');setPhone('');setTotal('');showToast('تم إنشاء عملية البيع')}catch(e:any){showToast(e.message)}};
 const addPayment=async()=>{if(!selected||Number(payment)<=0)return;try{const r=await apiService.recordSalePayment(selected.id,{amount:Number(payment),method:'cash'});setSales(v=>v.map(x=>x.id===selected.id?r.sale:x));setSelected(r.sale);setPayment('');showToast(`تم تسجيل الدفعة • المتبقي ${money(r.sale.balance)}`)}catch(e:any){showToast(e.message)}};
 return <div dir="rtl" className="space-y-5"><div className="p-6 rounded-3xl bg-gradient-to-l from-slate-900 to-emerald-950/30 border border-emerald-500/20 flex justify-between"><div><h2 className="text-xl font-black text-white flex gap-2 items-center"><ShoppingCart className="w-5 h-5 text-emerald-400"/> مركز المبيعات والتقسيط</h2><p className="text-xs text-slate-400 mt-1">دورة البيع والتحصيل الفعلية على الخادم.</p></div><button onClick={()=>void load()} className="px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-xs font-bold flex gap-2 items-center"><RefreshCw className={loading?'animate-spin':''}/> تحديث</button></div>
 <section className="panel"><h3 className="title"><Plus/> إنشاء عملية بيع</h3><div className="grid md:grid-cols-3 gap-2"><input className="input" placeholder="اسم العميل" value={customerName} onChange={e=>setCustomerName(e.target.value)}/><input className="input" placeholder="رقم الهاتف" value={phone} onChange={e=>setPhone(e.target.value)}/><select className="input" value={productId} onChange={e=>{setProductId(e.target.value);const p=products.find(x=>x.id===e.target.value);if(p)setTotal(String(p.cashPrice||''))}}><option value="">المنتج</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="input" type="number" value={total} onChange={e=>setTotal(e.target.value)} placeholder="قيمة البيع د.ع"/><input className="input" type="number" value={down} onChange={e=>setDown(e.target.value)} placeholder="الدفعة الأولى"/><input className="input" type="number" min="1" max="60" value={months} onChange={e=>setMonths(e.target.value)} placeholder="الأشهر"/><button className="btn md:col-span-3" onClick={()=>void create()}><Plus/> حفظ العملية</button></div></section>
 <section className="panel"><h3 className="title">آخر عمليات البيع</h3>{sales.length===0?<p className="text-xs text-slate-500">لا توجد عمليات بيع.</p>:sales.map(s=><div className="row" key={s.id}><div><b>{s.customerName}</b><span>{s.productName} • {money(s.totalAmount)} • {s.months} شهر</span></div><div className="flex items-center gap-2"><span className="text-[10px] text-cyan-300">متبقي {money(s.balance)}</span><button className="btn-small" onClick={()=>setSelected(s)}>تحصيل</button></div></div>)}</section>
 {selected&&<section className="panel border-emerald-500/20"><div className="flex justify-between"><h3 className="title mb-0">كشف {selected.customerName}</h3><button onClick={()=>setSelected(null)} className="text-xs text-slate-500">إغلاق</button></div><div className="grid grid-cols-2 md:grid-cols-4 gap-2 mt-4"><div className="stat">الإجمالي<br/><b>{money(selected.totalAmount)}</b></div><div className="stat">المقدم<br/><b>{money(selected.downPayment)}</b></div><div className="stat">المدفوع<br/><b>{money(selected.paidAmount)}</b></div><div className="stat">المتبقي<br/><b>{money(selected.balance)}</b></div></div>{selected.balance>0?<div className="flex gap-2 mt-4"><input className="input flex-1" type="number" min="1" value={payment} onChange={e=>setPayment(e.target.value)} placeholder="قيمة الدفعة"/><button className="btn" onClick={()=>void addPayment()}><Banknote/> تسجيل</button></div>:<p className="text-xs text-emerald-300 mt-4 flex gap-2"><CheckCircle2/> تم السداد بالكامل.</p>}</section>}
 <style>{`.panel{background:#0f172a;border:1px solid #1e293b;border-radius:18px;padding:18px}.title{font-weight:900;color:white;margin-bottom:14px;display:flex;gap:7px;align-items:center}.title svg{width:16px}.input{background:#020617;border:1px solid #334155;border-radius:12px;padding:.7rem;color:white;font-size:.75rem;outline:none;width:100%}.btn{background:#10b981;color:#022c22;border-radius:12px;padding:.7rem .9rem;font-size:.75rem;font-weight:900;display:flex;align-items:center;justify-content:center;gap:.35rem}.btn-small{background:#1e293b;color:#e2e8f0;border:1px solid #334155;border-radius:10px;padding:.45rem .7rem;font-size:.7rem;font-weight:800}.row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 0;border-bottom:1px solid #1e293b;font-size:.75rem}.row:last-child{border-bottom:0}.row div:first-child{display:flex;flex-direction:column;gap:3px}.row b{color:white}.row span{font-size:.68rem;color:#64748b}.stat{background:#020617;border:1px solid #1e293b;border-radius:12px;padding:10px;color:#64748b;font-size:.65rem}.stat b{color:white;font-size:.78rem}`}</style></div>;
};
