import React, { useEffect, useState } from 'react';
import { CreditCard, Plus, RefreshCw, Wallet, ReceiptText } from 'lucide-react';
import { apiService } from '../../services/api';
const money=(n:number)=>Number(n||0).toLocaleString('ar-IQ')+' د.ع';
export const FinanceView:React.FC=()=>{
 const [sales,setSales]=useState<any[]>([]); const [m,setM]=useState<any>({}); const [busy,setBusy]=useState(false); const [form,setForm]=useState({customerName:'',phone:'',productName:'',totalAmount:'',downPayment:'',months:'12'}); const [selected,setSelected]=useState<any>(null); const [pay,setPay]=useState('');
 const load=async()=>{setBusy(true);try{const [s,x]=await Promise.all([apiService.getSales(),apiService.getFinanceOverview()]);setSales(s);setM(x)}finally{setBusy(false)}}; useEffect(()=>{void load()},[]);
 const create=async()=>{if(!form.productName||!form.totalAmount)return;await apiService.createSale({...form,totalAmount:Number(form.totalAmount),downPayment:Number(form.downPayment||0),months:Number(form.months||1)});setForm({customerName:'',phone:'',productName:'',totalAmount:'',downPayment:'',months:'12'});await load()};
 const payment=async()=>{if(!selected||!pay)return;await apiService.recordSalePayment(selected.id,{amount:Number(pay),method:'cash'});setPay('');setSelected(null);await load()};
 return <div className="space-y-6" dir="rtl"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-white">المبيعات والتقسيط</h1><p className="text-sm text-slate-400 mt-1">دفتر مركزي لعمليات البيع والدفعات والأرصدة — بدون Gemini.</p></div><button disabled={busy} onClick={()=>void load()} className="btn-primary"><RefreshCw className="w-4 h-4"/> تحديث</button></div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{[['المبيعات',m.salesCount],['إجمالي المبيعات',money(m.totalSales)],['المحصّل',money(m.collected)],['المستحق',money(m.receivable)],['أقساط نشطة',m.activeInstallments]].map(([a,b])=><div className="p-4 rounded-2xl bg-slate-900 border border-slate-800" key={String(a)}><p className="text-xs text-slate-400">{a}</p><p className="text-xl font-black text-white mt-2">{b||0}</p></div>)}</div>
 <div className="grid lg:grid-cols-3 gap-5"><section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-black text-white mb-4 flex items-center gap-2"><Plus className="w-4 h-4 text-emerald-400"/> عملية بيع جديدة</h3><div className="grid gap-2">{[['customerName','اسم العميل'],['phone','رقم الهاتف'],['productName','اسم المنتج'],['totalAmount','قيمة البيع'],['downPayment','الدفعة الأولى'],['months','عدد الأشهر']].map(([k,p])=><input key={k} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={p} type={['totalAmount','downPayment','months'].includes(k)?'number':'text'} className="input"/>)}<button onClick={()=>void create()} className="btn-primary mt-2"><ReceiptText className="w-4 h-4"/> حفظ العملية</button></div></section>
 <section className="lg:col-span-2 p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-black text-white mb-4 flex items-center gap-2"><CreditCard className="w-4 h-4 text-cyan-400"/> دفتر العمليات</h3><div className="space-y-2">{sales.length===0?<p className="text-sm text-slate-500 py-10 text-center">لا توجد عمليات بيع بعد.</p>:sales.map(s=><div key={s.id} className="p-4 rounded-xl bg-slate-950 border border-slate-800 flex flex-col sm:flex-row sm:items-center gap-3 justify-between"><div><p className="font-black text-white">{s.customerName} • {s.productName}</p><p className="text-xs text-slate-400 mt-1">الإجمالي {money(s.totalAmount)} • {s.months} شهر • {s.status}</p></div><div className="text-left"><p className="font-black text-emerald-300">متبقي {money(s.balance)}</p><button onClick={()=>setSelected(s)} className="text-xs text-cyan-300 mt-1">تسجيل دفعة</button></div></div>)}</div></section></div>
 {selected&&<div className="fixed inset-0 z-50 bg-black/70 flex items-center justify-center p-4"><div className="w-full max-w-md bg-slate-900 border border-slate-700 rounded-2xl p-5"><h3 className="font-black text-white">تسجيل دفعة</h3><p className="text-sm text-slate-400 mt-2">الرصيد: {money(selected.balance)}</p><input autoFocus value={pay} onChange={e=>setPay(e.target.value)} type="number" placeholder="قيمة الدفعة" className="input mt-4"/><div className="flex gap-2 mt-4"><button onClick={()=>void payment()} className="btn-primary flex-1"><Wallet className="w-4 h-4"/> تسجيل</button><button onClick={()=>setSelected(null)} className="px-4 rounded-xl bg-slate-800 text-white">إلغاء</button></div></div></div>}</div>
}
