import React,{useEffect,useMemo,useState} from 'react';
import {apiService} from '../../services/api';
import {useApp} from '../../context/AppContext';
import {Building2,ReceiptText,Truck,WalletCards,FileSignature,CalendarClock,RefreshCw,Plus,Trash2,PackagePlus} from 'lucide-react';
const money=(n:number)=>`${Math.round(n||0).toLocaleString('ar-IQ')} د.ع`;
export const BusinessSuiteView:React.FC=()=>{
 const {showToast}=useApp(); const [tab,setTab]=useState('overview'); const [data,setData]=useState<any>({}); const [suppliers,setSuppliers]=useState<any[]>([]); const [purchases,setPurchases]=useState<any[]>([]); const [expenses,setExpenses]=useState<any[]>([]); const [contracts,setContracts]=useState<any[]>([]); const [sales,setSales]=useState<any[]>([]); const [schedule,setSchedule]=useState<any[]>([]); const [products,setProducts]=useState<any[]>([]); const [loading,setLoading]=useState(false);
 const [supplierName,setSupplierName]=useState(''),[supplierPhone,setSupplierPhone]=useState(''); const [expenseAmount,setExpenseAmount]=useState(''),[expenseDesc,setExpenseDesc]=useState(''),[expenseCat,setExpenseCat]=useState('تشغيل'); const [supplierId,setSupplierId]=useState(''),[productId,setProductId]=useState(''),[purchaseQty,setPurchaseQty]=useState('1'),[unitCost,setUnitCost]=useState(''); const [contractSale,setContractSale]=useState('');
 const load=async()=>{setLoading(true);try{const [o,s,p,e,c,sa,sch,pr]=await Promise.all([apiService.getBusinessOverview(),apiService.getSuppliers(),apiService.getPurchases(),apiService.getExpenses(),apiService.getContracts(),apiService.getSales(),apiService.getInstallmentSchedule(),apiService.getWorkspaceProducts()]);setData(o);setSuppliers(s);setPurchases(p);setExpenses(e.expenses||[]);setContracts(c);setSales(sa);setSchedule(sch);setProducts(pr)}catch(e:any){showToast(e.message||'تعذر تحميل مركز الأعمال')}finally{setLoading(false)}}; useEffect(()=>{void load()},[]);
 const selectedProduct=useMemo(()=>products.find(x=>x.id===productId),[products,productId]);
 const addSupplier=async()=>{try{const x=await apiService.createSupplier({name:supplierName,phone:supplierPhone});setSuppliers(v=>[x,...v]);setSupplierName('');setSupplierPhone('');showToast('تمت إضافة المورد')}catch(e:any){showToast(e.message)}};
 const addPurchase=async()=>{if(!supplierId||!selectedProduct){showToast('اختر المورد والمنتج');return}try{const x=await apiService.createPurchase({supplierId,items:[{productId:selectedProduct.id,productName:selectedProduct.name,quantity:Number(purchaseQty),unitCost:Number(unitCost)}]});setPurchases(v=>[x,...v]);showToast('تم تسجيل الشراء وتحديث المخزون');await load()}catch(e:any){showToast(e.message)}};
 const addExpense=async()=>{try{const x=await apiService.createExpense({amount:Number(expenseAmount),description:expenseDesc,category:expenseCat});setExpenses(v=>[x,...v]);setExpenseAmount('');setExpenseDesc('');showToast('تم تسجيل المصروف')}catch(e:any){showToast(e.message)}};
 const addContract=async()=>{const sale=sales.find(x=>x.id===contractSale);if(!sale){showToast('اختر عملية بيع');return}try{const x=await apiService.createContract({saleId:sale.id,customerName:sale.customerName,phone:sale.phone});setContracts(v=>[x,...v]);showToast(`تم إنشاء العقد ${x.contractNumber}`)}catch(e:any){showToast(e.message)}};
 const generate=async(id:string)=>{try{const rows=await apiService.generateInstallmentSchedule(id);setSchedule(v=>[...v.filter(x=>x.saleId!==id),...rows]);showToast('تم إنشاء جدول الأقساط')}catch(e:any){showToast(e.message)}};
 const cards=[['الموردون',data.suppliers,Building2],['المشتريات',money(data.purchaseTotal),PackagePlus],['المصروفات',money(data.expenseTotal),ReceiptText],['العقود',data.contracts,FileSignature],['الأقساط المستحقة',data.overdueInstallments,CalendarClock]];
 return <div dir="rtl" className="space-y-5"><div className="p-6 rounded-3xl bg-gradient-to-l from-slate-900 to-cyan-950/30 border border-cyan-500/20 flex justify-between gap-3"><div><h2 className="text-xl font-black text-white flex items-center gap-2"><Building2 className="w-5 h-5 text-cyan-400"/> مركز الأعمال المتكامل</h2><p className="text-xs text-slate-400 mt-1">الموردون والمشتريات والمصروفات والعقود وجدولة الأقساط في نواة تشغيل واحدة.</p></div><button onClick={()=>void load()} className="px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-xs font-bold flex items-center gap-2"><RefreshCw className={loading?'animate-spin':''}/> تحديث</button></div>
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{cards.map(([l,v,I])=><div className="p-4 rounded-2xl bg-slate-900 border border-slate-800" key={String(l)}><I className="w-4 h-4 text-cyan-400 mb-2"/><p className="text-[10px] text-slate-500">{l}</p><p className="text-lg font-black text-white">{String(v??0)}</p></div>)}</div>
 <div className="flex gap-2 overflow-x-auto">{[['overview','نظرة عامة'],['suppliers','الموردون'],['purchases','المشتريات'],['expenses','المصروفات'],['contracts','العقود'],['installments','الأقساط']].map(([id,l])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap ${tab===id?'bg-cyan-500 text-slate-950':'bg-slate-900 border border-slate-800 text-slate-300'}`}>{l}</button>)}</div>
 {tab==='overview'&&<section className="grid md:grid-cols-2 gap-4"><div className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-black text-white mb-4">صحة الدورة المالية</h3><div className="space-y-3 text-xs text-slate-300"><p>إجمالي المشتريات: <b className="text-white">{money(data.purchaseTotal)}</b></p><p>إجمالي المصروفات: <b className="text-white">{money(data.expenseTotal)}</b></p><p>قيمة الأقساط المتأخرة: <b className="text-rose-300">{money(data.overdueValue)}</b></p><p>عدد جداول الأقساط: <b className="text-white">{data.installments||0}</b></p></div></div><div className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-black text-white mb-4">إجراء سريع</h3><div className="grid grid-cols-2 gap-2"><button onClick={()=>setTab('suppliers')} className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-bold text-white">إدارة الموردين</button><button onClick={()=>setTab('purchases')} className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-bold text-white">تسجيل شراء</button><button onClick={()=>setTab('expenses')} className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-bold text-white">تسجيل مصروف</button><button onClick={()=>setTab('contracts')} className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-bold text-white">إدارة العقود</button></div></div></section>}
 {tab==='suppliers'&&<section className="space-y-4"><div className="panel"><h3 className="title">إضافة مورد</h3><div className="grid md:grid-cols-3 gap-2"><input className="input" value={supplierName} onChange={e=>setSupplierName(e.target.value)} placeholder="اسم المورد"/><input className="input" value={supplierPhone} onChange={e=>setSupplierPhone(e.target.value)} placeholder="الهاتف"/><button className="btn" onClick={()=>void addSupplier()}><Plus/> إضافة</button></div></div><div className="panel"><h3 className="title">الموردون ({suppliers.length})</h3>{suppliers.map(x=><div className="row" key={x.id}><div><b>{x.name}</b><span>{x.phone||'لا يوجد هاتف'}</span></div><button onClick={async()=>{try{await apiService.deleteSupplier(x.id);setSuppliers(v=>v.filter(y=>y.id!==x.id));showToast('تم حذف المورد')}catch(e:any){showToast(e.message)}}}><Trash2/></button></div>)}</div></section>}
 {tab==='purchases'&&<section className="space-y-4"><div className="panel"><h3 className="title">تسجيل شراء واستلام للمخزون</h3><div className="grid md:grid-cols-5 gap-2"><select className="input" value={supplierId} onChange={e=>setSupplierId(e.target.value)}><option value="">المورد</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className="input" value={productId} onChange={e=>setProductId(e.target.value)}><option value="">المنتج</option>{products.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className="input" type="number" min="1" value={purchaseQty} onChange={e=>setPurchaseQty(e.target.value)} placeholder="الكمية"/><input className="input" type="number" min="0" value={unitCost} onChange={e=>setUnitCost(e.target.value)} placeholder="سعر الوحدة"/><button className="btn" onClick={()=>void addPurchase()}><Truck/> استلام</button></div></div><div className="panel"><h3 className="title">آخر المشتريات</h3>{purchases.map(x=><div className="row" key={x.id}><div><b>{money(x.total)}</b><span>{x.items?.map((i:any)=>`${i.productName} × ${i.quantity}`).join('، ')}</span></div><span>{new Date(x.createdAt).toLocaleDateString('ar-IQ')}</span></div>)}</div></section>}
 {tab==='expenses'&&<section className="space-y-4"><div className="panel"><h3 className="title">تسجيل مصروف</h3><div className="grid md:grid-cols-4 gap-2"><input className="input" type="number" value={expenseAmount} onChange={e=>setExpenseAmount(e.target.value)} placeholder="المبلغ د.ع"/><select className="input" value={expenseCat} onChange={e=>setExpenseCat(e.target.value)}>{['تشغيل','رواتب','نقل','تسويق','إيجار','خدمات','أخرى'].map(x=><option key={x}>{x}</option>)}</select><input className="input" value={expenseDesc} onChange={e=>setExpenseDesc(e.target.value)} placeholder="الوصف"/><button className="btn" onClick={()=>void addExpense()}><WalletCards/> تسجيل</button></div></div><div className="panel"><h3 className="title">سجل المصروفات</h3>{expenses.map(x=><div className="row" key={x.id}><div><b>{money(x.amount)}</b><span>{x.category} • {x.description}</span></div><button onClick={async()=>{try{await apiService.deleteExpense(x.id);setExpenses(v=>v.filter(y=>y.id!==x.id));showToast('تم حذف المصروف')}catch(e:any){showToast(e.message)}}}><Trash2/></button></div>)}</div></section>}
 {tab==='contracts'&&<section className="space-y-4"><div className="panel"><h3 className="title">إنشاء عقد من عملية بيع</h3><div className="grid md:grid-cols-2 gap-2"><select className="input" value={contractSale} onChange={e=>setContractSale(e.target.value)}><option value="">اختر عملية البيع</option>{sales.map(x=><option key={x.id} value={x.id}>{x.customerName} — {money(x.totalAmount||x.subtotal)}</option>)}</select><button className="btn" onClick={()=>void addContract()}><FileSignature/> إنشاء عقد</button></div></div><div className="panel"><h3 className="title">العقود</h3>{contracts.map(x=><div className="row" key={x.id}><div><b>{x.contractNumber}</b><span>{x.customerName} • {x.status}</span></div>{x.status==='draft'&&<button className="btn-small" onClick={async()=>{try{const c=await apiService.signContract(x.id);setContracts(v=>v.map(y=>y.id===x.id?c:y));showToast('تم توقيع العقد وتسجيل المرجع')}catch(e:any){showToast(e.message)}}}>توقيع</button>}</div>)}</div></section>}
 {tab==='installments'&&<section className="panel"><h3 className="title">جداول الأقساط</h3><div className="space-y-2">{sales.filter(x=>Number(x.financedAmount||0)>0).map(x=><div className="row" key={x.id}><div><b>{x.customerName}</b><span>{money(x.financedAmount)} • {x.months||0} شهر</span></div><button className="btn-small" onClick={()=>void generate(x.id)}>إنشاء/تحديث الجدول</button></div>)}</div><div className="mt-5 border-t border-slate-800 pt-4">{schedule.slice(0,50).map(x=><div className="row" key={x.id}><div><b>القسط {x.sequence}</b><span>{new Date(x.dueAt).toLocaleDateString('ar-IQ')}</span></div><span>{money(x.amount)} • {x.status}</span></div>)}</div></section>}
 <style>{`.panel{background:#0f172a;border:1px solid #1e293b;border-radius:18px;padding:18px}.title{font-weight:900;color:white;margin-bottom:14px}.input{background:#020617;border:1px solid #334155;border-radius:12px;padding:.7rem;color:white;font-size:.75rem;outline:none;width:100%}.btn{background:#22d3ee;color:#082f49;border-radius:12px;padding:.7rem .9rem;font-size:.75rem;font-weight:900;display:flex;align-items:center;justify-content:center;gap:.35rem}.btn svg,.btn-small svg{width:15px;height:15px}.btn-small{background:#1e293b;color:#e2e8f0;border:1px solid #334155;border-radius:10px;padding:.45rem .7rem;font-size:.7rem;font-weight:800}.row{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 0;border-bottom:1px solid #1e293b;color:#cbd5e1;font-size:.75rem}.row:last-child{border-bottom:0}.row div{display:flex;flex-direction:column;gap:3px}.row b{color:white}.row span{font-size:.68rem;color:#64748b}.row>button:not(.btn-small){background:transparent;color:#64748b;border:0;padding:6px}.row>button:not(.btn-small):hover{color:#fb7185}`}</style></div>
};
