import React, { useCallback, useEffect, useState } from 'react';
import { Activity, Archive, CheckCircle2, Download, FileCheck2, Loader2, PlugZap, RefreshCw, ShieldCheck, TimerReset, TriangleAlert } from 'lucide-react';
import { apiService } from '../../services/api';
import { useApp } from '../../context/AppContext';

export const SystemControlView: React.FC = () => {
  const { currentUser, showToast } = useApp();
  const [deployment, setDeployment] = useState<any>(null); const [health, setHealth] = useState<any>(null); const [integrity, setIntegrity] = useState<any>(null);
  const [overview, setOverview] = useState<any>(null); const [diagnostics, setDiagnostics] = useState<any>(null); const [alerts, setAlerts] = useState<any[]>([]); const [backups, setBackups] = useState<any[]>([]); const [audit, setAudit] = useState<any[]>([]); const [loading, setLoading] = useState(false);
  // فحص اتصال Gemini: يدوي فقط، مرة واحدة لكل ضغطة، ولا يُشغَّل تلقائياً عند
  // تحميل الصفحة. الزر محصور بالمالك في هذه الواجهة، والحماية الحقيقية على الخادم.
  const [geminiTesting, setGeminiTesting] = useState(false);
  const [geminiResult, setGeminiResult] = useState<{ ok: boolean; message: string; hint?: string | null } | null>(null);
  const runGeminiTest = useCallback(async () => {
    if (geminiTesting) return;
    setGeminiTesting(true); setGeminiResult(null);
    try { setGeminiResult(await apiService.verifyGeminiProvider()); }
    finally { setGeminiTesting(false); }
  }, [geminiTesting]);
  const load = useCallback(async () => { setLoading(true); try { const [h,i,o,b,a,d,al]=await Promise.all([apiService.checkHealth(),apiService.getSystemIntegrity().catch((e)=>({healthy:false,error:e.message})),apiService.getControlOverview().catch(()=>null),apiService.listSystemBackupsDetailed().catch(()=>({backups:[]})),apiService.getControlAudit(25).catch(()=>[]),apiService.getSystemDiagnostics().catch(()=>null),apiService.getSystemAlerts().catch(()=>[]),apiService.getDeploymentChecklist().catch(()=>null)]); setHealth(h);setIntegrity(i);setOverview(o);setDiagnostics(d);setAlerts(al);setBackups(b.backups||[]);setAudit(a||[]);} finally{setLoading(false);} },[]);
  useEffect(()=>{void load()},[load]);
  if(currentUser?.role!=='owner') return <div className="p-8 rounded-2xl bg-slate-900 border border-slate-800 text-center text-slate-300">هذا المركز مخصص لمالك النظام فقط.</div>;
  const checks: [string, boolean][] = integrity?.checks ? (Object.entries(integrity.checks) as [string, boolean][]) : [];
  const labels:Record<string,string>={stateFile:'ملف الحالة',stateWritable:'قابلية الكتابة',ownerConfigured:'مالك النظام مضبوط',googleAudienceCheckConfigured:'تحقق Google مضبوط',platformConnectionsPersisted:'حفظ الاتصالات',workspaceLoaded:'مساحة العمل',backupDirectory:'مجلد النسخ الاحتياطية'};
  const cards:any[]=[['الخادم',health?.status==='ok'?'يعمل':'غير جاهز',Activity],['Gemini',health?.aiEnabled?'مفعّل':'غير مفعّل',ShieldCheck],['المهام',overview?`${overview.jobs?.queued||0} انتظار`:'—',TimerReset],['النسخ الاحتياطية',`${backups.length}/7`,Archive]];
  return <div className="space-y-6">
    <div className="p-6 rounded-2xl bg-gradient-to-l from-slate-900 to-emerald-950/50 border border-emerald-500/20 flex flex-col md:flex-row justify-between gap-4"><div><h2 className="text-xl font-black text-white flex items-center gap-2"><ShieldCheck className="w-5 h-5 text-emerald-400"/> مركز التشغيل والحماية</h2><p className="text-xs text-slate-400 mt-1">فحص حالة الخادم، سلامة البيانات، النسخ الاحتياطية وسجل العمليات من مكان واحد.</p></div><div className="flex gap-2"><button onClick={()=>void load()} disabled={loading} className="px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-xs font-bold text-white flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/> تحديث الفحص</button><button onClick={async()=>{try{await apiService.exportSystemBackup();showToast('تم تصدير النسخة الاحتياطية دون الأسرار')}catch(e:any){showToast(e.message)}}} className="px-4 py-2 rounded-xl bg-emerald-500 text-slate-950 text-xs font-black flex items-center gap-2"><Download className="w-4 h-4"/> تصدير نسخة</button></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{cards.map(([label,value,Icon])=><div key={label} className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><Icon className="w-5 h-5 text-emerald-400 mb-3"/><p className="text-xs text-slate-400">{label}</p><p className="text-lg font-black text-white mt-1">{value}</p></div>)}</div>
    <section className="p-5 rounded-2xl bg-slate-900 border border-slate-800">
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div><h3 className="font-bold text-white flex items-center gap-2"><PlugZap className="w-4 h-4 text-emerald-400"/> فحص مزود Gemini</h3><p className="text-[10px] text-slate-500 mt-1">إثبات اتصال النموذج الإنتاجي المعتمد بطلب حقيقي واحد، ومع ضغط المزود (503) يُثبت الاتصال بمرشح GA شقيق ويُعرض الموديل العامل فعلاً. لا يُشغَّل تلقائياً عند تحديث الصفحة. هذا الفحص منفصل تماماً عن Google Sign-In.</p></div>
        <button onClick={()=>void runGeminiTest()} disabled={geminiTesting} className="px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-xs font-bold text-white flex items-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed">{geminiTesting?<Loader2 className="w-4 h-4 animate-spin"/>:<PlugZap className="w-4 h-4"/>} {geminiTesting?'جارٍ اختبار الاتصال...':'اختبار اتصال Gemini'}</button>
      </div>
      {geminiResult&&<div className={`mt-4 p-3 rounded-xl border flex items-start gap-2 ${geminiResult.ok?'bg-emerald-500/10 border-emerald-500/30':'bg-rose-500/10 border-rose-500/30'}`}>{geminiResult.ok?<CheckCircle2 className="w-4 h-4 text-emerald-400 mt-0.5"/>:<TriangleAlert className="w-4 h-4 text-rose-400 mt-0.5"/>}<div className="text-xs"><p className={geminiResult.ok?'text-emerald-300 font-bold':'text-rose-300 font-bold'}>{geminiResult.ok?'نجاح':'فشل'}</p><p className="text-slate-300 mt-1">{geminiResult.message}</p>{geminiResult.hint&&<p className="text-[10px] text-amber-300/90 mt-1 leading-relaxed">التوجيه التشخيصي: {geminiResult.hint}</p>}</div></div>}
    </section>
    {deployment&&<section className="p-5 rounded-2xl bg-slate-900 border border-emerald-500/20"><div className="flex items-center justify-between mb-4"><div><h3 className="font-bold text-white">قائمة الإنهاء والتشغيل الحقيقي</h3><p className="text-[10px] text-slate-500 mt-1">لا تعتبر المنصة جاهزة إلا بعد تحقق المزود الفعلي.</p></div><span className={`px-3 py-1 rounded-full text-[10px] font-black ${deployment.ready?'bg-emerald-500/15 text-emerald-400':'bg-amber-500/15 text-amber-400'}`}>{deployment.ready?'جاهز من ناحية النظام':'يحتاج إكمال إعدادات'}</span></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-2 mb-4">{(deployment.checks||[]).map((c:any)=><div key={c.id} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800 flex justify-between"><span className="text-xs text-slate-300">{c.label}</span>{c.ok?<CheckCircle2 className="w-4 h-4 text-emerald-400"/>:<TriangleAlert className="w-4 h-4 text-amber-400"/>}</div>)}</div><div className="grid md:grid-cols-2 gap-2">{(deployment.platforms||[]).map((x:any)=><div key={x.platform} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800"><div className="flex justify-between"><span className="text-xs font-bold text-white">{x.name}</span><span className="text-[10px] text-slate-500">{x.productionReady?'إنتاجي':x.connected?'متصل':'غير متصل'}</span></div>{x.missing?.length>0&&<p className="text-[10px] text-amber-400 mt-1">المطلوب: {x.missing.join('، ')}</p>}<p className="text-[10px] text-slate-500 mt-1">{x.next}</p></div>)}</div></section>}
    {alerts.length>0&&<section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-bold text-white mb-3">تنبيهات التشغيل</h3><div className="grid md:grid-cols-2 gap-2">{alerts.map((a:any)=><div key={a.id} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800"><p className="text-xs font-bold text-slate-200">{a.title}</p><p className="text-[10px] text-slate-500 mt-1">{a.detail}</p></div>)}</div></section>}
    {diagnostics&&<section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-bold text-white mb-3">التشخيص التشغيلي</h3><div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-xs">{[['الإصدار',diagnostics.version],['Node',diagnostics.node],['وقت التشغيل',`${diagnostics.uptimeSeconds}s`],['الجلسات',diagnostics.sessions],['المنتجات',diagnostics.workspace.products],['المحتوى',diagnostics.workspace.posts],['المحادثات',diagnostics.workspace.conversations],['المهام',diagnostics.jobs.total]].map(([k,v])=><div key={String(k)} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800"><p className="text-slate-500">{k}</p><p className="text-white font-bold mt-1 truncate">{String(v)}</p></div>)}</div></section>}
    <div className="grid lg:grid-cols-2 gap-6"><section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-bold text-white flex items-center gap-2 mb-4"><FileCheck2 className="w-4 h-4 text-emerald-400"/> سلامة النظام</h3><div className="space-y-2">{checks.map(([key,ok])=><div key={key} className="flex items-center justify-between p-3 rounded-xl bg-slate-950/60 border border-slate-800"><span className="text-xs text-slate-300">{labels[key]||key}</span>{ok?<CheckCircle2 className="w-4 h-4 text-emerald-400"/>:<TriangleAlert className="w-4 h-4 text-amber-400"/>}</div>)}</div></section><section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><h3 className="font-bold text-white flex items-center gap-2 mb-4"><Archive className="w-4 h-4 text-cyan-400"/> آخر النسخ الاحتياطية</h3>{backups.length===0?<p className="text-xs text-slate-500">لا توجد نسخ احتياطية بعد.</p>:<div className="space-y-2 max-h-64 overflow-auto">{backups.map((b:any)=><div key={b.name} className="p-3 rounded-xl bg-slate-950/60 border border-slate-800"><p className="text-xs text-white font-mono truncate">{b.name}</p><p className="text-[10px] text-slate-500 mt-1">{b.size?`${b.size} بايت`:''} • {b.modifiedAt||''}</p></div>)}</div>}</section></div>
    <section className="p-5 rounded-2xl bg-slate-900 border border-slate-800"><div className="flex justify-between mb-4"><h3 className="font-bold text-white">آخر العمليات الموثقة</h3><span className="text-[10px] text-slate-500">{audit.length} سجل</span></div>{audit.length===0?<p className="text-xs text-slate-500">لا توجد عمليات مسجلة.</p>:<div className="space-y-2">{audit.slice(0,12).map((x:any)=><div key={x.id} className="grid grid-cols-[1fr_auto] gap-3 p-3 rounded-xl bg-slate-950/60 border border-slate-800"><div><p className="text-xs text-slate-200 font-bold">{x.action}</p><p className="text-[10px] text-slate-500 truncate">{x.detail||'—'}</p></div><span className="text-[10px] text-slate-500 whitespace-nowrap">{x.at?new Date(x.at).toLocaleString('ar-IQ'):''}</span></div>)}</div>}</section>
  </div>;
};
